In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
data=pd.DataFrame(digits.data)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data,digits.target,test_size=0.2)

In [17]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression(max_iter=10000)
logr.fit(X_train,y_train)
logr.score(X_test,y_test)

0.9638888888888889

In [16]:
from sklearn.tree import DecisionTreeClassifier
dectree=DecisionTreeClassifier()
dectree.fit(X_train,y_train)
dectree.score(X_test,y_test)

0.8722222222222222

In [9]:
from sklearn.ensemble import RandomForestClassifier
rand=RandomForestClassifier(n_estimators=10)
rand.fit(X_train, y_train)
rand.score(X_test,y_test)

0.9638888888888889

In [10]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train, y_train)
svc.score(X_test,y_test)

0.9916666666666667

In [18]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [35]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [36]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
score_log=[]
score_dec=[]
score_rand=[]
score_svc=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train,X_test,y_train,y_test= digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_log.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
    score_dec.append(get_score(DecisionTreeClassifier(),X_train,X_test,y_train,y_test))
    score_rand.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    score_svc.append(get_score(SVC(),X_train,X_test,y_train,y_test))

In [37]:
score_log

[0.9248747913188647, 0.9415692821368948, 0.9232053422370617]

In [38]:
score_dec

[0.7278797996661102, 0.8196994991652755, 0.7445742904841403]

In [39]:
score_svc

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [40]:
score_rand

[0.9449081803005008, 0.9499165275459098, 0.9215358931552587]

In [45]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target, cv=3)

array([0.92487479, 0.94156928, 0.92320534])

In [46]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target, cv=3)

array([0.9115192 , 0.95158598, 0.92821369])

In [47]:
cross_val_score(DecisionTreeClassifier(),digits.data,digits.target, cv=3)

array([0.73789649, 0.80467446, 0.77963272])

In [48]:
cross_val_score(SVC(),digits.data,digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])